### ISSUE TITLE
Undocumented usage of environment variables

### ISSUE THREAD

**Issue by locnnil** [canonical/matter-snap-testing#14]
The environment variables:

`SERVICE_CHANNEL`
`LOCAL_SERVICE_SNAP`
`SKIP_TEARDOWN_REMOVAL`

Aren't documented at the `README.md` file, or in any other place rather than in the [commentaries in the code](https://github.com/canonical/matter-snap-testing/blob/c15a6cdfc5419f574ce928f0ab1d29bab4cd37fd/utils/env.go#L11):

**Comment by farshidtz** [comment]
The variables need to change to drop SERVICE keyword, leftover from EdgeX.

**Comment by MonicaisHer** [comment]
For reference, the available environment variables are listed in these README files:
- https://github.com/canonical/edgex-snap-testing?tab=readme-ov-file
- https://github.com/canonical/openthread-border-router-snap/tree/main/tests#override-behavior

**Comment by farshidtz** [comment]
Ideally, this should be documented in code only for easier maintenance. The [go doc badge](https://pkg.go.dev/badge/?path=https%3A%2F%2Fgithub.com%2Fcanonical%2Fmatter-snap-testing) should be added to the README, along with hyperlinks to any other useful section.
